### ISSUE TITLE
Caption spacing is different for loa, ndn, appendices and idependence notice

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#118]
## Description

The position of the title of the LoA is a bit too low (in comparison to the titles of ToC and LoF).

## How to reproduce

1. You can see the difference when reading the PDF: [starter-recommended.pdf](https://github.com/skyfrk/dhbw-vs-latex-template/blob/68056d16a6c61696304afa505df4789fba26daab/examples/starter-recommended/starter-recommended.pdf)
(The view should be adjusted to the size of a complete page.)

## Screenshots

![grafik](https://user-images.githubusercontent.com/13857929/90312913-81490480-df08-11ea-931d-ccb7e768835c.png)

**Comment by skyfrk** [comment]
This is apparently also the case for `Sperrvermerk`, `Anhang #` and `Selbstständigkeitserklärung`.
