### ISSUE TITLE
Title page should have default geometry.

### ISSUE THREAD

**Issue by MrcoSchrnr** [Skyfr3ak/dhbw-vs-latex-template#12]
the title shouldn't be formatted like the rest of the document

use following to fix it: 

\newgeometry{
left=3cm,
right=3cm,
top=2cm,
bottom=4cm,
bindingoffset=5mm
}

%Content for title

\restoregeometry

**Comment by skyfrk** [comment]
Correct. I wrote the template white a folder like this one in mind:
![image](https://user-images.githubusercontent.com/27026029/60596794-ff505780-9da9-11e9-9c83-5d6285275361.png)

However that standard use-case should be like you described.
