### ISSUE TITLE
Pagination required on table of content pages?

### ISSUE THREAD

**Issue by MrcoSchrnr** [Skyfr3ak/dhbw-vs-latex-template#13]
There shouldn't be a pagecounter on the tableofcontent

**Comment by skyfrk** [comment]
During the feedback session regarding my personal PA1 Mrs. Heinrich told me to add a pagination number to the table of contents. Therefore I added it again.

Now I'm confused as to what's correct. Maybe you could mail her for an official answer?

If we have to remove the pagination on the table of contents again we can reuse the [old code](https://github.com/skyfrk/dhbw-vs-latex-template/commit/09d18b62bc9dfbc339df94ff6c11bc028d068321). Feel free to submit an PR!

**Comment by MrcoSchrnr** [comment]
I'm pretty sure that the pagination number should not be at the table of contents. I remeber that we said this at some exercises where we saw a table of contents with pagination number
![image](https://user-images.githubusercontent.com/39101494/60707252-98e34a80-9f0b-11e9-891e-7fee7e2bd8ab.png)
See script Mrs. Heinrich

**Comment by robingenz** [comment]
Also had no page number on my table of contents and everything was fine.
