### ISSUE TITLE
Footnote is not fixed at the bottom

### ISSUE THREAD

**Issue by MrcoSchrnr** [Skyfr3ak/dhbw-vs-latex-template#14]

**Comment by skyfrk** [comment]
Can you provide steps to reproduce the bug? I just built the template and it works fine for me:

![image](https://user-images.githubusercontent.com/27026029/60596063-81d81780-9da8-11e9-95c1-976a75ea2b94.png)

Feel free to open the issue again!

**Comment by MrcoSchrnr** [comment]
i don't know how it will happen again but i fixed it with "\usepackage[bottom]{footmisc}" at citestyle %custom footcite command

**Comment by bluecoder24** [comment]
@skyfrk we talked about this issue earlier this day, now it occured again. Maybe you can now reproduce the bug with my example.

```
\subsection{Teststufen}

Der Test eines Softwaresystems erfolgt stets in mehreren Teststufen, die häufig an den Entwicklungsstand 
des Systems angelehnt sind. Damit eine bestimmte Funktionalität frühestmöglich getestet werden kann,
müssen die Teststufen und die jeweiligen Tests eindeutig abgegrenzt werden.\myfootcite[Vgl.][S. 75]{teststufen}

\begin{figure}[ht] % ht means that the figure should appear at this exact position
    \centering
    \caption{Klassische Teststufen}
    \includegraphics[width=\textwidth]{teststufen.png} % put your pictures into content/assets
    \caption*{\footnotesize{Eigene
    Darstellung in Anlehnung an Witte, Frank, Testmanagement und Softwaretest, 2019, S. 75 ff.}}
    
    \label{fig:teststufen} % add a reference label
    \end{figure}

Abgeleitet von den in \autoref{fig:teststufen} dargestellten Teststufen wurde für das Projekt ein individuelles Teststufenkonzept entwickelt.

\subsubsection{IT-interner Funktionstest}
```

<img width="363" alt="bug_pdf" src="https://user-images.githubusercontent.com/50449809/61539053-e64ad600-aa3a-11e9-82d0-17f24af3a650.png">

EDIT: Fixed it for the moment as MrcoSchrnr explained.

**Comment by skyfrk** [comment]
@bluecoder24 I will merge @MrcoSchrnr 's fix ;)
