### ISSUE TITLE
Fix bibstyle according to the script of Mrs. Heinrich

### ISSUE THREAD

**Issue by MrcoSchrnr** [Skyfr3ak/dhbw-vs-latex-template#19]
![image](https://user-images.githubusercontent.com/39101494/60876829-f1cd1e80-a23c-11e9-9a34-05b6c8838ce3.png)
like that in script of mrs. heinrich

**Comment by MrcoSchrnr** [comment]
additional there should ne author**:** ...

**Comment by skyfrk** [comment]
![grafik](https://user-images.githubusercontent.com/27026029/60900495-9024a880-a26c-11e9-94ab-fa3a1a318c3e.png)

Hm, this is also in her script. She didn't complain about the way it is right now...

Do you know how to add the colons?

As for the parentheses we have to edit [this](https://github.com/skyfrk/dhbw-vs-latex-template/blob/1dfe79820ada2f6c6da14a779c7c5e88fb820188/misc/dhbw-bibstyle.tex#L19) code.

**Comment by skyfrk** [comment]
I'll close this issue as the current code is compliant with the current spec from Mrs. Heinrich.
