### ISSUE TITLE
Fix footnote formatting for long author names

### ISSUE THREAD

**Issue by MrcoSchrnr** [Skyfr3ak/dhbw-vs-latex-template#21]
![image](https://user-images.githubusercontent.com/39101494/60969881-fec33e00-a320-11e9-83b0-40faf3a08088.png)

**Comment by skyfrk** [comment]
Didn't she say that it is ok to use "et al" when there are more than three authors? I can't find anything regarding this issue in her script. Where do you have your information from?

**Comment by MrcoSchrnr** [comment]
sorry my bad ^^ but in this case it dont look that good with that footnote

**Comment by skyfrk** [comment]
Correct, but I don't know how to fix it :/
