### ISSUE TITLE
Page margins don't match the new specifications

### ISSUE THREAD

**Issue by bluecoder24** [Skyfr3ak/dhbw-vs-latex-template#25]
According to the new 2019 script the following page margins must be followed:

> Abstand: oben 4,0 cm, unten 2,0 cm, links 4,0  cm, rechts 2,0 cm

Currently it's:
`  \usepackage[a4paper,lmargin={4cm},rmargin={1.5cm},tmargin={2.5cm},bmargin={2cm}]`

Looks like this has changed with the new script....

**Comment by skyfrk** [comment]
Haha, I like this update 😄! This reduces the size of a page which means that we have to write less pages!

Go ahead and submit a PR! Ah and could you also upload the new script somewhere? Maybe there are even more changes!

**Comment by MrcoSchrnr** [comment]
I guess the new script is only for WI18 and following. WI17 has to use the script that mrs. heinrich shared us.
