### ISSUE TITLE
Misplaced alignment tab character &

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#49]
**Describe the bug**
I got the following error when compiling one of the examples:
```
[2] [3] (./starter-recommended.lof) [4] (./starter-recommended.lot) [5] (./starter-recommended.lol) [6] [1]
c:/Users/robin.genz/Entwicklung/latex-test/starter-recommended.tex:35: Misplaced alignment tab character &.
\do #1->\bbx@tab@label {#1}\addcolon &
                                       \bbx@tab@item {#1}\\
l.35 \end{document}
```

**To Reproduce**
1. Install the latest version of TeX Live / VS Code / LaTeX Workshop.
2. Execute the installation script `install_udhbwvst_tl.ps1`.
3. Open an example (e.g. `/examples/starter-recommended/`) in VS Code and run one of predefined LaTeX Workshop recipes (`.vscode/settings.json`).

**Annotation**: This error does not occur when removing the `&` from `\def\do##1{\bbx@tab@label{##1}\addcolon & \bbx@tab@item{##1}\\}%` ([L331](https://github.com/skyfrk/dhbw-vs-latex-template/blob/master/src/udhbwvst.cls#L331)).

**Expected behavior**
This error should not occur when compiling the LaTeX document.

**Additional context**
```
$ ver
Microsoft Windows [Version 10.0.18362.295]

$ latexmk --version
Latexmk, John Collins, 18 June 2019. Version 4.65

$ biber --version
biber version: 2.13

$ lualatex --version
This is LuaTeX, Version 1.10.0 (TeX Live 2019/W32TeX)
```

**Comment by skyfrk** [comment]
Thank you for this exemplary issue!

I tried to reproduce your problem but I wasn't successful :/

1. I downloaded the `v4.2.0` release artifact.
2. I installed `udhbwvst` running `install_udhbwvst_tl.ps1`.
3. I built the pdf in VSCode using the `latexmk` build recipe.

There were no compilation errors! My setup:

```shell
$ ver
Microsoft Windows [Version 10.0.17763.678]

$ latexmk --version
Latexmk, John Collins, 17 March 2019. Version 4.63b

$ biber --version
biber version: 2.12

$ lualatex --version
This is LuaTeX, Version 1.10.0 (TeX Live 2019/W32TeX)
```

I tried the same again using the official docker image:

`docker run -v C:\path\to\starter-recommended:/work skyfrk/udhbwvst:4.2.0 latexmk -synctex=1 -interaction=nonstopmode -file-line-error -shell-escape -pdf -pdflatex=lualatex starter-recommended.tex`

Versions of latexmk, biber and lualatex inside the docker container:

```shell
$ docker run --rm -it skyfrk/udhbwvst:4.2.0 latexmk --version
Latexmk, John Collins, 17 March 2019. Version 4.63b

$ docker run --rm -it skyfrk/udhbwvst:4.2.0 biber --version
biber version: 2.12

$ docker run --rm -it skyfrk/udhbwvst:4.2.0 lualatex --version
This is LuaTeX, Version 1.10.0 (TeX Live 2019/Arch Linux)
```

I have absolutely no idea what causes your compilation error :(

Can you do an insanity check for me and check the versions of latexmk, biber and lualatex inside the docker container on your end? 😬

**Comment by robingenz** [comment]
Sure, this is my output:
```
$ docker run --rm -it skyfrk/udhbwvst:4.2.0 latexmk --version
Latexmk, John Collins, 17 March 2019. Version 4.63b

$ docker run --rm -it skyfrk/udhbwvst:4.2.0 biber --version
biber version: 2.12

$ docker run --rm -it skyfrk/udhbwvst:4.2.0 lualatex --version
This is LuaTeX, Version 1.10.0 (TeX Live 2019/Arch Linux)
```
The docker container works fine. 

I think there should be a problem with `biber version: 2.13` or `Latexmk, Version 4.65`.

**Comment by skyfrk** [comment]
I'll try to update my setup and reproduce the bug again!

**Comment by skyfrk** [comment]
I was able to reproduce your issue. I think it's beause of `biber v2.12 -> v2.13` as builds with the non-`latexmk` recipe also don't work.

From the [biber changelog](https://github.com/plk/biber/blob/35e3f755f91656e6695256f6f07febfc7f0b6deb/Changes#L13):

> biber now exits with error on some very malformed names instead of skipping them as this can lead to data loss in bibliographies.

Maybe this has something to do with this issue.

I'll try to provide a fix asap! One could fix this problem by replacing the custom `longtable` style with a style similar to Mrs. Heinrichs style (from her script):

![image](https://user-images.githubusercontent.com/27026029/64500651-a55f9700-d2f0-11e9-8595-66423e7c098a.png)

Stick to the docker image in the mean time 😬

**Comment by robingenz** [comment]
I think with these examples she just wanted to show what must be included.
This example was related to the structure:  
  
![image](https://user-images.githubusercontent.com/13857929/64506894-725dd900-d2d9-11e9-9735-3ed0e6306cc3.png)  
  
So the previous format should be retained.

**Comment by skyfrk** [comment]
I guess you're right. I'll try to replace the current implementation of a tabular bibliography with [this](https://github.com/moewew/biblatex-ext) package.
