### ISSUE TITLE
problem with plural acronyms

### ISSUE THREAD

**Issue by MrcoSchrnr** [Skyfr3ak/dhbw-vs-latex-template#56]
## Description

When I use \acp{acronym} it create in the pdf ac and acp
![image](https://user-images.githubusercontent.com/39101494/66133879-b356be00-e5f7-11e9-8ef9-58eb9ef2f723.png)

## How to reproduce

1. declare an acronym with plural
2. use this acronym plural in text

## Screenshots

![image](https://user-images.githubusercontent.com/39101494/66134178-31b36000-e5f8-11e9-9330-c4fa9266afc0.png)

**Comment by skyfrk** [comment]
How did you define the acronym? Did you read the [documentation](http://mirrors.ctan.org/macros/latex/contrib/acro/acro_en.pdf) of the acro package?

**Comment by MrcoSchrnr** [comment]
![image](https://user-images.githubusercontent.com/39101494/66188051-9f0dd200-e686-11e9-876c-11d897279a4a.png)

**Comment by skyfrk** [comment]
I just looked at the docs of the acro package (page 3). TL;DR: use `short-plural-form` and `long-plural-form` instead of `short-plural` and `long-plural`. I'll update the docs when I have access to a PC.

**Comment by robingenz** [comment]
`short-plural-form` and `long-plural-form` don't work for me (v4.5.2).  
Examples:  
```
\DeclareAcronym{IIS}{%
    short     = IIS,
    long      = Internet Information Service
}

\acp{IIS}
```
-> `Internet Information Services (sIISs)`  
  
```
\DeclareAcronym{IIS}{%
    short     = IIS,
    short-plural-form = IIS,
    long      = Internet Information Service
}

\acp{IIS}
```
-> `Internet Information Services (sIIS)` 
  
```
\DeclareAcronym{IIS}{%
    short     = IIS,
    short-plural-form = IIS,
    long      = Internet Information Service
    long-plural-form = Internet Information Services,
}

\acp{IIS}
```
-> No output - hangs on build... (I canceled the compilation after 310 seconds)

**Comment by skyfrk** [comment]
The first two examples behave correct if `\ac{}` was used before. I didn't find a bug for this weird behaviour in the [official repo](https://bitbucket.org/cgnieder/acro/issues?q=acp). Maybe you can add one?

In your last example you missed a comma ;)
