### ISSUE TITLE
Cover page and the non-disclosure notice habe no page numbers (in PDF readers)

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#57]
## Description

The cover page and the non-disclosure notice have no page numbers in the PDF reader.

Possible solution: The letters a and b as numbering for both pages.

## How to reproduce

1. Open the file "starter-recommended.pdf" in Adobe Acrobat DC.

## Screenshots

![grafik](https://user-images.githubusercontent.com/13857929/67801426-6f859600-fa89-11e9-9c53-3d88fd5f1835.png)

**Comment by skyfrk** [comment]
> The cover page and the non-disclosure notice have no page numbers in the PDF reader.

I think that this is the expected behaviour. These pages don't have a page number. Why do you think that a non-semantic page number should be displayed here?

**Comment by robingenz** [comment]
Every page should be directly accessible in a PDF reader! 
This is very important for usability.
For example, books (in PDF format) often use "C1" as the page number for the cover page.
Arabic numbers and Roman numerals are already taken. That's why I would suggest letters. But we can also choose anything else.

**Comment by skyfrk** [comment]
>Every page should be directly accessible in a PDF reader!

Got it!
