### ISSUE TITLE
PDF file is corrupted (Adobe Acrobat DC)

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#58]
## Description

Adobe Acrobat DC displays the following error message (see the screenshot) when opening a PDF file based on this template.

## How to reproduce

1. Open the file "starter-recommended.pdf" in Adobe Acrobat DC.

## Screenshots

![grafik](https://user-images.githubusercontent.com/13857929/67801090-c8086380-fa88-11e9-8e72-20b92b0e2ca5.png)

## Additional context

This issue might be related to #57 .

**Comment by skyfrk** [comment]
Amazing error message 😅. Are there more detailed logs available?

**Comment by robingenz** [comment]
Unfortunately, I could not find any logs. 
I think it's related to #57. I recommend to fix #57 first.

**Comment by skyfrk** [comment]
Looks like the bug was introduced between `v2.1.7` and `v2.2.0`. Adobe Acrobat DC starts complaining from `v2.2.0` on...
