### ISSUE TITLE
TOC should have a roman 1 ("I") as the page number

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#59]
## Description

The toc should have the page number "I" as specified by Mrs. Heinrich. In her pdf file is a roman 2 ("II"), but she said that this is not up to date and we should use the roman 1 ("I").

Furthermore, the page number is not displayed in the PDF reader.

## How to reproduce

1. Open the file "starter-recommended.pdf" in Adobe Acrobat DC.

## Screenshots

![grafik](https://user-images.githubusercontent.com/13857929/67802514-92b14500-fa8b-11e9-80a6-3d164ca1d9dc.png)

![grafik](https://user-images.githubusercontent.com/13857929/67802531-9b098000-fa8b-11e9-9c02-3fc20086a56d.png)

## Additional context

This issue might be related to #57 .

**Comment by skyfrk** [comment]
Do we have something like a citation from Gruber to back this?

**Comment by robingenz** [comment]
The current Red Grubert ("2019_Roter-Grubert_19-08-14") contains an example for TOC (on page 56). 
In this example the following page has the Roman number **two** as the page number.
![grafik](https://user-images.githubusercontent.com/13857929/67894804-9e6b3d00-fb59-11e9-86f4-fa9f6172ed8f.png)


I also found the following in my notes:
![grafik](https://user-images.githubusercontent.com/13857929/67893335-b55c6000-fb56-11e9-8903-927e4ab573ca.png)
