### ISSUE TITLE
Contents of the LOA and LOL should not be indented

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#60]
## Description

The contents of the LOA and LOL should not be indented (like LOF).

## How to reproduce

1. Open the file "full.pdf" (based on "full.tex").

## Screenshots

![grafik](https://user-images.githubusercontent.com/13857929/67804501-5b449780-fa8f-11e9-82c4-d33c1aa7fde0.png)

![grafik](https://user-images.githubusercontent.com/13857929/67804571-76170c00-fa8f-11e9-8c47-e038f012c67e.png)

![grafik](https://user-images.githubusercontent.com/13857929/67804585-7e6f4700-fa8f-11e9-927b-4e198f5a79a6.png)

**Comment by skyfrk** [comment]
I already tried to fix both indentations and I didn't succeed 😥

If you want to try to fix the issue you have to deal with [this code](https://github.com/skyfrk/dhbw-vs-latex-template/blob/19e34637eae753a4c5999cb18c6ed1d5a96313c0/src/udhbwvst.cls#L153) for the LOA and try to understand the [listings](http://mirrors.ctan.org/macros/latex/contrib/listings/listings.pdf) package in depth.
