### ISSUE TITLE
Bibliography entries are displayed incorrectly

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#61]
## Description

The bibliography entries are displayed incorrectly (see screenshots).
There are four issues:
1. There should be no colon after the last authors name.
2. There should be no semicolon between several author names.
3. There should not be a dot at the end of an entry.
4. The brackets should not be angular but round.

## How to reproduce

1. Add an bibliography entry.
For example:
```
@book{testmanagement-droste-merz,
    author      = {Oliver Droste and Christina Merz},
    title       = {Testmanagement in der Praxis},
    shorttitle  = {Testmanagement in der Praxis},
    year        = {2019},
    publisher   = {Springer Vieweg},
    location    = "{Berlin/Heidelberg}"
}
```

## Screenshots

Current behavior:
![grafik](https://user-images.githubusercontent.com/13857929/67806979-33a3fe00-fa94-11e9-99ab-44ae9df69793.png)

Correct behavior (from Mrs. Heinrich PDF file):
![grafik](https://user-images.githubusercontent.com/13857929/67805853-11a97c00-fa92-11e9-831a-4ea4fd7f1838.png)

**Comment by skyfrk** [comment]
![image](https://user-images.githubusercontent.com/27026029/67863940-1f5c1180-fb25-11e9-8b43-635b9a5455ff.png)

From the screenshot:

> Die Trennzeichen zwischen den einzelnen Angaben sind nicht normiert!

## Regarding your issues

> There should be no colon after the last authors name.

There is a colon in her example.

> There should be no semicolon between several author names.

As cited above: There is no separator defined.

> There should not be a dot at the end of an entry.

This one could be true but I don't know for sure. There were dots at the end of my bib entries in my PA1 and Mrs. Heinrich didn't complain about it.

> The brackets should not be angular but round.

I think that there should be rectangular brackets as in the screenshot above.

**Comment by robingenz** [comment]
> Die Trennzeichen zwischen den einzelnen Angaben sind nicht normiert!

Okay. 

> There is a colon in her example.

In my opinion, this example should only show what must be included and not how it should be displayed.
In terms of presentation, the following screenshot should be more meaningful:
![grafik](https://user-images.githubusercontent.com/13857929/67805853-11a97c00-fa92-11e9-831a-4ea4fd7f1838.png)

We also used this style in her exercises. Example:
![grafik](https://user-images.githubusercontent.com/13857929/67892068-37975500-fb54-11e9-9173-9b6d585baccf.png)

Annotation: If we decide to remove the colon, I would suggest removing the semicolon between multiple author names as well, since it fits much better.

> This one could be true but I don't know for sure. There were dots at the end of my bib entries in my PA1 and Mrs. Heinrich didn't complain about it.

Okay, then it's fine.

> I think that there should be rectangular brackets as in the screenshot above.

As written above: In my opinion, this example should only show what must be included and not how it should be displayed.

**Comment by skyfrk** [comment]
Ok, so our TODO here is:

- [x] Remove colon after last author name
- [x] Remove period after bib entry
- [x] Replace `;` as multi author delimitor with some kind of new line character
- [x] Replace brackets around the keyword with parentheses

**Comment by skyfrk** [comment]
![image](https://user-images.githubusercontent.com/27026029/69534505-4407a580-0f7a-11ea-926d-b1dc1cb06401.png)

In the most recent `Empfehlungen zur Anfertigung von Projekt- und Bachelorarbeiten` by `Prof. Dr. Thomas Grubert` (2013/2014) there is always a dot at the end of an bibliography entry. 😑
