### ISSUE TITLE
Cover page has a wrong style

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#62]
## Description

The cover page has a wrong style (see screenshots).

## How to reproduce

1. Open the PDF file "starter-recommended.pdf".

## Screenshots

Example of current cover page:
![grafik](https://user-images.githubusercontent.com/13857929/67810028-183bf180-fa9a-11e9-9a01-5fce6680c2c4.png)

Example of correct cover page (from Mrs. Heinrich PDF file):
![grafik](https://user-images.githubusercontent.com/13857929/67810113-3efa2800-fa9a-11e9-836a-630451d7c5a1.png)

Description from Mrs. Heinrich:
![grafik](https://user-images.githubusercontent.com/13857929/67810261-900a1c00-fa9a-11e9-9514-390884b191e6.png)

**Comment by skyfrk** [comment]
> (die letzten drei Elemente en bloc unten auf der Seite, s. Beispiel)

Oh. This could be a problem.

**Comment by robingenz** [comment]
It would probably be easiest to copy her template. This would ensure that it can not be faulty.
