### ISSUE TITLE
Missing dot after source information (dhbwfigure)

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#63]
## Description

The source information of an image must end with a dot.

## How to reproduce

1. Open the file "full.pdf" (based on full.tex).

## Screenshots

Current behavior...
Example 1:
![grafik](https://user-images.githubusercontent.com/13857929/68036533-28d0af80-fcc6-11e9-9bc3-285aadde01d9.png)
Example 2:
![grafik](https://user-images.githubusercontent.com/13857929/68036843-c5934d00-fcc6-11e9-819f-8539c4fbe90f.png)

Correct behavior:
![grafik](https://user-images.githubusercontent.com/13857929/68036553-36863500-fcc6-11e9-9d64-562db8abf861.png)

Descriptions from Mrs. Heinrich...
On page 15:
![grafik](https://user-images.githubusercontent.com/13857929/68036682-73eac280-fcc6-11e9-9964-307a9d4240ae.png)
On page 16:
![grafik](https://user-images.githubusercontent.com/13857929/68036597-50277c80-fcc6-11e9-9170-af4369258be4.png)

**Comment by skyfrk** [comment]
I don't think that it's the responsibility of `dhbwfigure` or `\dhbwFigure` but the responsibility of the `\cite` command and your responsiblity if you provide a custom text like `Eigene Darstellung.`. I'll look into the `\cite` command and check if it is possible to add a dot at the end of the output. I hope that `\cite` is intelligent enough to not print a second dot if a dot already is the last character of a source like `some words, o.J.`... 🙈
