### ISSUE TITLE
Publish template as package on CTAN

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#64]
## Description

It would be great if this template were available as an official ctan package. This would make the setup easier.
For example, the template "iodhbwm" is also available as a ctan package: https://www.ctan.org/pkg/iodhbwm

## Recommended solution

Add this template as a package to the official sources of ctan.

**Comment by skyfrk** [comment]
Uploading this package will require a lot of changes and improvements:

* https://ctan.org/help/upload-pkg
* https://ctan.org/file/help/ctan/CTAN-upload-addendum

Tools:

* https://ctan.org/pkg/pkgcheck
* https://ctan.org/pkg/ctan-o-mat

TODOs:

* Add error handling (#38)
* Create a script which builds a valid CTAN package `.zip` file with (#73):
  * [correct file structure](https://ctan.org/help/upload-pkg)
  * UTF-8 english `README.md` which clearly specifies the license
  * Documentation in `PDF` format 😑
* Clarify if the package can legally contain the DHBW-VS logo
