### ISSUE TITLE
Page number has too much space on the right

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#69]
## Description

The page numbers have too much space on the right (see screenshot).

## How to reproduce

1. Add a page with page number

```
\geometry{%
    a4paper,
    tmargin = {2.5cm},
    bmargin = {2cm},
    lmargin = {4cm},
    rmargin = {1.5cm}
}
```

## Screenshots

![Unbenannt](https://user-images.githubusercontent.com/13857929/68992727-69582d80-086f-11ea-87e2-96916a63ff2c.jpg)

**Comment by skyfrk** [comment]
OK, I think this is weird side effect. This template uses the `fancyhdr` package to display the page number. When I align the page number or anything on the left in the header there is no gap but if I try to algin something to the right there is this gap. See, this MWE works just fine:

```tex
\documentclass{article}

\usepackage{geometry}
\usepackage{showframe}
\usepackage{fancyhdr}

\geometry{%
    a4paper,
    tmargin = {2.5cm},
    bmargin = {2cm},
    lmargin = {4cm},
    rmargin = {1.5cm}
}

\pagestyle{fancy}
\fancyhf{}
\fancyhead[R]{\thepage}
\renewcommand{\headrulewidth}{0pt} % No line below the page number
\setlength{\headheight}{\baselineskip}

\begin{document}
    LOL
\end{document}
```
![image](https://user-images.githubusercontent.com/27026029/68993884-11282800-087d-11ea-97a5-49ab7ea5b5ed.png)

I'll look into it later!
