### ISSUE TITLE
Subsubsubsections are not listed in the table of contents

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#88]
## Description

[Subsubsubsections](https://github.com/skyfrk/dhbw-vs-latex-template/blob/master/docs/writing.md#subsections) (`\paragraph{title}`) are not listed in the table of contents.

## How to reproduce

1. Code: 
```
\section{The title of the next section}
\subsection{The title of my subsection}
\subsubsection{The title of my subsubsection}
\paragraph{The title of my subsubsubsection}
```

## Screenshots

![grafik](https://user-images.githubusercontent.com/13857929/78133135-34afd180-741e-11ea-80fe-0c3ff327cc71.png)

**Comment by skyfrk** [comment]
This behaviour is intended as the default depth is `3`:

![image](https://user-images.githubusercontent.com/27026029/78134185-04693280-7420-11ea-915e-052de1b0e280.png)

You can adjust the depth of the table of contents by calling `\setcounter{tocdepth}{4}` (see https://tex.stackexchange.com/a/17879/166545) in your preamble.

We should add this to the documentation... 🙈

**Comment by robingenz** [comment]
Oh great, thank you!
