### ISSUE TITLE
print-ndn causes build to fail

### ISSUE THREAD

**Issue by bluecoder24** [Skyfr3ak/dhbw-vs-latex-template#90]
## Description

When setting print-ndn = false the build fails and several incomprehensible errors appear.
For example: "Undefined control sequence" line 68 in uhdhbwvst-title-default.def, for details see screenshot below.

## How to reproduce

1. Set print-ndn = false
2. Build LaTex project

## Screenshots

![image](https://user-images.githubusercontent.com/50449809/80600668-0a593000-8a2d-11ea-9143-371ac1d1cea9.png)

## Additional context

I tried defining a new title page completely without the ifbool-Block for printing the ndn, the bug still appears.

**Comment by skyfrk** [comment]
I was able to reproduce and fix the bug.

Disabling `print-ndn` led to `rotating` and `textpos` packages not being loaded. I'll release the fix asap.
