### ISSUE TITLE
feature request: support longtable

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#94]
## Description

The `longtable` loses padding inside the `dhbwtable` environment.

## How to reproduce

1. Insert code: 
```
\begin{dhbwtable}{caption={Allgemeine Anforderungen an das Modul},label=tab:test,source={Eigene Darstellung.},float=h}
    \begin{longtable}{ | p{0.05\linewidth} | p{0.70\linewidth} | p{0.15\linewidth} | }
        \hline
        \textbf{ID} & \textbf{Beschreibung} & \textbf{Priorität} \\ \hline
        1 & Es wird ein Signaling-Server für den Signalisierungsprozess benötigt. & 1 \\ \hline
    \end{longtable}
\end{dhbwtable}
```

## Screenshots

With dhbwtable environment:
![grafik](https://user-images.githubusercontent.com/13857929/80944586-32a8ac00-8dea-11ea-9e78-abb9903bc87b.png)

Without dhbwtable environment:
![grafik](https://user-images.githubusercontent.com/13857929/80944652-5835b580-8dea-11ea-8808-e4592a54c164.png)

**Comment by skyfrk** [comment]
I have no idea what is happening here. But using `longtable` in `dhbwtable` doesn't make any sense in the first place:

The `dhbwtable` environment is essentially a wrapper around the LaTeX `table` environment. The `table` environment is a floating environment which is configured not to break on pagebreaks. `longtable` also provides a floating environment, but this one is configured to break on pagebreaks to enable longer than page-long tables. So there is basically no point in using `longtable` inside a `table` environment. Read more about that [here](https://tex.stackexchange.com/questions/227402/issue-in-using-longtable-within-table-environment).

I will reframe this issue to be a feature request for a `dhbwlongtable` environment which also provides footnotes and captions just like the `dhbwtable` environment.

**Comment by robingenz** [comment]
Sounds good, thank you!
