### ISSUE TITLE
table counter is incorrect when using longtable

### ISSUE THREAD

**Issue by robingenz** [Skyfr3ak/dhbw-vs-latex-template#95]
## Description

The table counter is incorrect when using `longtable` inside of the `dhbwtable` environment.

## How to reproduce

1. Code: 
```
\begin{dhbwtable}{caption={Evilplan},label=tab:mytable1,source={aaa},float=h}
    \begin{longtable}{ | c | l |}
        \hline
        \textbf{Phase}  & \textbf{Action}       \\ \hline
        1               & Use a latex template  \\ \hline
        2               & ???                   \\ \hline
        3               & Profit!               \\ \hline
    \end{longtable}
\end{dhbwtable}

\begin{dhbwtable}{caption={Evilplan},label=tab:mytable2,source={aaa},float=h}
    \begin{longtable}{ | c | l |}
        \hline
        \textbf{Phase}  & \textbf{Action}       \\ \hline
        1               & Use a latex template  \\ \hline
        2               & ???                   \\ \hline
        3               & Profit!               \\ \hline
    \end{longtable}
\end{dhbwtable}
```

## Screenshots

The table counter jumps from one to three:
![grafik](https://user-images.githubusercontent.com/13857929/80952281-b918ba00-8df9-11ea-9854-0e907dad9650.png)

**Comment by skyfrk** [comment]
`dhbwtable` is a wrapper around `table`. `table` increments the table count. `longtable` is an alternative to `table`. `longtable` also increments the table count. Thats why the table count is always incremented twice. 🙈

`longtable` should not be used inside `dhbwtable`.

Proper `longtable` support is about to be integrated in `udhbwvst`. See #94 .
